package com.yc;

import org.apache.ibatis.annotations.Param;

import com.other.BaseMapper;
import com.other.DateTask;
import com.other.DateTaskExample;
import com.other.DateTaskKey;

public interface DateTaskMapper extends BaseMapper<DateTaskExample, DateTask, DateTaskKey> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DateTask record, @Param("example") DateTaskExample example);
}