package com.other;

import java.io.Serializable;

public class DateTaskKey extends BaseDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_task.date_task_id
     *
     * @mbggenerated
     */
    private String dateTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table date_task
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column date_task.date_task_id
     *
     * @return the value of date_task.date_task_id
     *
     * @mbggenerated
     */
    public String getDateTaskId() {
        return dateTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column date_task.date_task_id
     *
     * @param dateTaskId the value for date_task.date_task_id
     *
     * @mbggenerated
     */
    public void setDateTaskId(String dateTaskId) {
        this.dateTaskId = dateTaskId;
    }
}