package com.other;

import java.util.ArrayList;
import java.util.List;

public class DateTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table date_task
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table date_task
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table date_task
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public DateTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table date_task
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDateTaskIdIsNull() {
            addCriterion("date_task_id is null");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdIsNotNull() {
            addCriterion("date_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdEqualTo(String value) {
            addCriterion("date_task_id =", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdNotEqualTo(String value) {
            addCriterion("date_task_id <>", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdGreaterThan(String value) {
            addCriterion("date_task_id >", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("date_task_id >=", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdLessThan(String value) {
            addCriterion("date_task_id <", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdLessThanOrEqualTo(String value) {
            addCriterion("date_task_id <=", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdLike(String value) {
            addCriterion("date_task_id like", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdNotLike(String value) {
            addCriterion("date_task_id not like", value, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdIn(List<String> values) {
            addCriterion("date_task_id in", values, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdNotIn(List<String> values) {
            addCriterion("date_task_id not in", values, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdBetween(String value1, String value2) {
            addCriterion("date_task_id between", value1, value2, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskIdNotBetween(String value1, String value2) {
            addCriterion("date_task_id not between", value1, value2, "dateTaskId");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameIsNull() {
            addCriterion("date_task_name is null");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameIsNotNull() {
            addCriterion("date_task_name is not null");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameEqualTo(String value) {
            addCriterion("date_task_name =", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameNotEqualTo(String value) {
            addCriterion("date_task_name <>", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameGreaterThan(String value) {
            addCriterion("date_task_name >", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameGreaterThanOrEqualTo(String value) {
            addCriterion("date_task_name >=", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameLessThan(String value) {
            addCriterion("date_task_name <", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameLessThanOrEqualTo(String value) {
            addCriterion("date_task_name <=", value, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameIn(List<String> values) {
            addCriterion("date_task_name in", values, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameNotIn(List<String> values) {
            addCriterion("date_task_name not in", values, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameBetween(String value1, String value2) {
            addCriterion("date_task_name between", value1, value2, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andDateTaskNameNotBetween(String value1, String value2) {
            addCriterion("date_task_name not between", value1, value2, "dateTaskName");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNull() {
            addCriterion("service_name is null");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNotNull() {
            addCriterion("service_name is not null");
            return (Criteria) this;
        }

        public Criteria andServiceNameEqualTo(String value) {
            addCriterion("service_name =", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotEqualTo(String value) {
            addCriterion("service_name <>", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThan(String value) {
            addCriterion("service_name >", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("service_name >=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThan(String value) {
            addCriterion("service_name <", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThanOrEqualTo(String value) {
            addCriterion("service_name <=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLike(String value) {
            addCriterion("service_name like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotLike(String value) {
            addCriterion("service_name not like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameIn(List<String> values) {
            addCriterion("service_name in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotIn(List<String> values) {
            addCriterion("service_name not in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameBetween(String value1, String value2) {
            addCriterion("service_name between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotBetween(String value1, String value2) {
            addCriterion("service_name not between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(String value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(String value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(String value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(String value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(String value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(String value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLike(String value) {
            addCriterion("begin_time like", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotLike(String value) {
            addCriterion("begin_time not like", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<String> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<String> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(String value1, String value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(String value1, String value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andOpenFlgIsNull() {
            addCriterion("open_flg is null");
            return (Criteria) this;
        }

        public Criteria andOpenFlgIsNotNull() {
            addCriterion("open_flg is not null");
            return (Criteria) this;
        }

        public Criteria andOpenFlgEqualTo(String value) {
            addCriterion("open_flg =", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgNotEqualTo(String value) {
            addCriterion("open_flg <>", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgGreaterThan(String value) {
            addCriterion("open_flg >", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgGreaterThanOrEqualTo(String value) {
            addCriterion("open_flg >=", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgLessThan(String value) {
            addCriterion("open_flg <", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgLessThanOrEqualTo(String value) {
            addCriterion("open_flg <=", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgLike(String value) {
            addCriterion("open_flg like", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgNotLike(String value) {
            addCriterion("open_flg not like", value, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgIn(List<String> values) {
            addCriterion("open_flg in", values, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgNotIn(List<String> values) {
            addCriterion("open_flg not in", values, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgBetween(String value1, String value2) {
            addCriterion("open_flg between", value1, value2, "openFlg");
            return (Criteria) this;
        }

        public Criteria andOpenFlgNotBetween(String value1, String value2) {
            addCriterion("open_flg not between", value1, value2, "openFlg");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(Integer value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(Integer value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(Integer value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(Integer value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<Integer> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<Integer> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(Integer value1, Integer value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNull() {
            addCriterion("period_unit is null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNotNull() {
            addCriterion("period_unit is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitEqualTo(String value) {
            addCriterion("period_unit =", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotEqualTo(String value) {
            addCriterion("period_unit <>", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThan(String value) {
            addCriterion("period_unit >", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThanOrEqualTo(String value) {
            addCriterion("period_unit >=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThan(String value) {
            addCriterion("period_unit <", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThanOrEqualTo(String value) {
            addCriterion("period_unit <=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLike(String value) {
            addCriterion("period_unit like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotLike(String value) {
            addCriterion("period_unit not like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIn(List<String> values) {
            addCriterion("period_unit in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotIn(List<String> values) {
            addCriterion("period_unit not in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitBetween(String value1, String value2) {
            addCriterion("period_unit between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotBetween(String value1, String value2) {
            addCriterion("period_unit not between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andLastDateIsNull() {
            addCriterion("last_date is null");
            return (Criteria) this;
        }

        public Criteria andLastDateIsNotNull() {
            addCriterion("last_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastDateEqualTo(String value) {
            addCriterion("last_date =", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotEqualTo(String value) {
            addCriterion("last_date <>", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateGreaterThan(String value) {
            addCriterion("last_date >", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateGreaterThanOrEqualTo(String value) {
            addCriterion("last_date >=", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateLessThan(String value) {
            addCriterion("last_date <", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateLessThanOrEqualTo(String value) {
            addCriterion("last_date <=", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateLike(String value) {
            addCriterion("last_date like", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotLike(String value) {
            addCriterion("last_date not like", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateIn(List<String> values) {
            addCriterion("last_date in", values, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotIn(List<String> values) {
            addCriterion("last_date not in", values, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateBetween(String value1, String value2) {
            addCriterion("last_date between", value1, value2, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotBetween(String value1, String value2) {
            addCriterion("last_date not between", value1, value2, "lastDate");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgIsNull() {
            addCriterion("execute_flg is null");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgIsNotNull() {
            addCriterion("execute_flg is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgEqualTo(String value) {
            addCriterion("execute_flg =", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgNotEqualTo(String value) {
            addCriterion("execute_flg <>", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgGreaterThan(String value) {
            addCriterion("execute_flg >", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("execute_flg >=", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgLessThan(String value) {
            addCriterion("execute_flg <", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgLessThanOrEqualTo(String value) {
            addCriterion("execute_flg <=", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgLike(String value) {
            addCriterion("execute_flg like", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgNotLike(String value) {
            addCriterion("execute_flg not like", value, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgIn(List<String> values) {
            addCriterion("execute_flg in", values, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgNotIn(List<String> values) {
            addCriterion("execute_flg not in", values, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgBetween(String value1, String value2) {
            addCriterion("execute_flg between", value1, value2, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andExecuteFlgNotBetween(String value1, String value2) {
            addCriterion("execute_flg not between", value1, value2, "executeFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgIsNull() {
            addCriterion("immediate_execute_flg is null");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgIsNotNull() {
            addCriterion("immediate_execute_flg is not null");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgEqualTo(String value) {
            addCriterion("immediate_execute_flg =", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgNotEqualTo(String value) {
            addCriterion("immediate_execute_flg <>", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgGreaterThan(String value) {
            addCriterion("immediate_execute_flg >", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgGreaterThanOrEqualTo(String value) {
            addCriterion("immediate_execute_flg >=", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgLessThan(String value) {
            addCriterion("immediate_execute_flg <", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgLessThanOrEqualTo(String value) {
            addCriterion("immediate_execute_flg <=", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgLike(String value) {
            addCriterion("immediate_execute_flg like", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgNotLike(String value) {
            addCriterion("immediate_execute_flg not like", value, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgIn(List<String> values) {
            addCriterion("immediate_execute_flg in", values, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgNotIn(List<String> values) {
            addCriterion("immediate_execute_flg not in", values, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgBetween(String value1, String value2) {
            addCriterion("immediate_execute_flg between", value1, value2, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andImmediateExecuteFlgNotBetween(String value1, String value2) {
            addCriterion("immediate_execute_flg not between", value1, value2, "immediateExecuteFlg");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNull() {
            addCriterion("insert_datetime is null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIsNotNull() {
            addCriterion("insert_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeEqualTo(String value) {
            addCriterion("insert_datetime =", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotEqualTo(String value) {
            addCriterion("insert_datetime <>", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThan(String value) {
            addCriterion("insert_datetime >", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("insert_datetime >=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThan(String value) {
            addCriterion("insert_datetime <", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLessThanOrEqualTo(String value) {
            addCriterion("insert_datetime <=", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeLike(String value) {
            addCriterion("insert_datetime like", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotLike(String value) {
            addCriterion("insert_datetime not like", value, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeIn(List<String> values) {
            addCriterion("insert_datetime in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotIn(List<String> values) {
            addCriterion("insert_datetime not in", values, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeBetween(String value1, String value2) {
            addCriterion("insert_datetime between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertDatetimeNotBetween(String value1, String value2) {
            addCriterion("insert_datetime not between", value1, value2, "insertDatetime");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNull() {
            addCriterion("insert_user_id is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIsNotNull() {
            addCriterion("insert_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdEqualTo(String value) {
            addCriterion("insert_user_id =", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotEqualTo(String value) {
            addCriterion("insert_user_id <>", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThan(String value) {
            addCriterion("insert_user_id >", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("insert_user_id >=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThan(String value) {
            addCriterion("insert_user_id <", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLessThanOrEqualTo(String value) {
            addCriterion("insert_user_id <=", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdLike(String value) {
            addCriterion("insert_user_id like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotLike(String value) {
            addCriterion("insert_user_id not like", value, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdIn(List<String> values) {
            addCriterion("insert_user_id in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotIn(List<String> values) {
            addCriterion("insert_user_id not in", values, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdBetween(String value1, String value2) {
            addCriterion("insert_user_id between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertUserIdNotBetween(String value1, String value2) {
            addCriterion("insert_user_id not between", value1, value2, "insertUserId");
            return (Criteria) this;
        }

        public Criteria andInsertAppIsNull() {
            addCriterion("insert_app is null");
            return (Criteria) this;
        }

        public Criteria andInsertAppIsNotNull() {
            addCriterion("insert_app is not null");
            return (Criteria) this;
        }

        public Criteria andInsertAppEqualTo(String value) {
            addCriterion("insert_app =", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppNotEqualTo(String value) {
            addCriterion("insert_app <>", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppGreaterThan(String value) {
            addCriterion("insert_app >", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppGreaterThanOrEqualTo(String value) {
            addCriterion("insert_app >=", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppLessThan(String value) {
            addCriterion("insert_app <", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppLessThanOrEqualTo(String value) {
            addCriterion("insert_app <=", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppLike(String value) {
            addCriterion("insert_app like", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppNotLike(String value) {
            addCriterion("insert_app not like", value, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppIn(List<String> values) {
            addCriterion("insert_app in", values, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppNotIn(List<String> values) {
            addCriterion("insert_app not in", values, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppBetween(String value1, String value2) {
            addCriterion("insert_app between", value1, value2, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertAppNotBetween(String value1, String value2) {
            addCriterion("insert_app not between", value1, value2, "insertApp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpIsNull() {
            addCriterion("insert_user_ip is null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpIsNotNull() {
            addCriterion("insert_user_ip is not null");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpEqualTo(String value) {
            addCriterion("insert_user_ip =", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpNotEqualTo(String value) {
            addCriterion("insert_user_ip <>", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpGreaterThan(String value) {
            addCriterion("insert_user_ip >", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpGreaterThanOrEqualTo(String value) {
            addCriterion("insert_user_ip >=", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpLessThan(String value) {
            addCriterion("insert_user_ip <", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpLessThanOrEqualTo(String value) {
            addCriterion("insert_user_ip <=", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpLike(String value) {
            addCriterion("insert_user_ip like", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpNotLike(String value) {
            addCriterion("insert_user_ip not like", value, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpIn(List<String> values) {
            addCriterion("insert_user_ip in", values, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpNotIn(List<String> values) {
            addCriterion("insert_user_ip not in", values, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpBetween(String value1, String value2) {
            addCriterion("insert_user_ip between", value1, value2, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andInsertUserIpNotBetween(String value1, String value2) {
            addCriterion("insert_user_ip not between", value1, value2, "insertUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(String value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(String value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(String value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(String value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(String value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLike(String value) {
            addCriterion("update_datetime like", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotLike(String value) {
            addCriterion("update_datetime not like", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<String> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<String> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(String value1, String value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(String value1, String value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("update_user_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("update_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("update_user_id =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("update_user_id <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("update_user_id >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_id >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("update_user_id <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("update_user_id <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("update_user_id like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("update_user_id not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("update_user_id in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("update_user_id not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("update_user_id between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("update_user_id not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("update_app is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("update_app is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("update_app =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("update_app <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("update_app >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("update_app >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("update_app <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("update_app <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("update_app like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("update_app not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("update_app in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("update_app not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("update_app between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("update_app not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpIsNull() {
            addCriterion("update_user_ip is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpIsNotNull() {
            addCriterion("update_user_ip is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpEqualTo(String value) {
            addCriterion("update_user_ip =", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpNotEqualTo(String value) {
            addCriterion("update_user_ip <>", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpGreaterThan(String value) {
            addCriterion("update_user_ip >", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpGreaterThanOrEqualTo(String value) {
            addCriterion("update_user_ip >=", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpLessThan(String value) {
            addCriterion("update_user_ip <", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpLessThanOrEqualTo(String value) {
            addCriterion("update_user_ip <=", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpLike(String value) {
            addCriterion("update_user_ip like", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpNotLike(String value) {
            addCriterion("update_user_ip not like", value, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpIn(List<String> values) {
            addCriterion("update_user_ip in", values, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpNotIn(List<String> values) {
            addCriterion("update_user_ip not in", values, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpBetween(String value1, String value2) {
            addCriterion("update_user_ip between", value1, value2, "updateUserIp");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIpNotBetween(String value1, String value2) {
            addCriterion("update_user_ip not between", value1, value2, "updateUserIp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table date_task
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andDateTaskIdLikeInsensitive(String value) {
            addCriterion("upper(date_task_id) like", value.toUpperCase(), "dateTaskId");
            return this;
        }

        public Criteria andServiceNameLikeInsensitive(String value) {
            addCriterion("upper(service_name) like", value.toUpperCase(), "serviceName");
            return this;
        }

        public Criteria andBeginTimeLikeInsensitive(String value) {
            addCriterion("upper(begin_time) like", value.toUpperCase(), "beginTime");
            return this;
        }

        public Criteria andOpenFlgLikeInsensitive(String value) {
            addCriterion("upper(open_flg) like", value.toUpperCase(), "openFlg");
            return this;
        }

        public Criteria andPeriodUnitLikeInsensitive(String value) {
            addCriterion("upper(period_unit) like", value.toUpperCase(), "periodUnit");
            return this;
        }

        public Criteria andLastDateLikeInsensitive(String value) {
            addCriterion("upper(last_date) like", value.toUpperCase(), "lastDate");
            return this;
        }

        public Criteria andExecuteFlgLikeInsensitive(String value) {
            addCriterion("upper(execute_flg) like", value.toUpperCase(), "executeFlg");
            return this;
        }

        public Criteria andImmediateExecuteFlgLikeInsensitive(String value) {
            addCriterion("upper(immediate_execute_flg) like", value.toUpperCase(), "immediateExecuteFlg");
            return this;
        }

        public Criteria andInsertDatetimeLikeInsensitive(String value) {
            addCriterion("upper(insert_datetime) like", value.toUpperCase(), "insertDatetime");
            return this;
        }

        public Criteria andInsertUserIdLikeInsensitive(String value) {
            addCriterion("upper(insert_user_id) like", value.toUpperCase(), "insertUserId");
            return this;
        }

        public Criteria andInsertAppLikeInsensitive(String value) {
            addCriterion("upper(insert_app) like", value.toUpperCase(), "insertApp");
            return this;
        }

        public Criteria andInsertUserIpLikeInsensitive(String value) {
            addCriterion("upper(insert_user_ip) like", value.toUpperCase(), "insertUserIp");
            return this;
        }

        public Criteria andUpdateDatetimeLikeInsensitive(String value) {
            addCriterion("upper(update_datetime) like", value.toUpperCase(), "updateDatetime");
            return this;
        }

        public Criteria andUpdateUserIdLikeInsensitive(String value) {
            addCriterion("upper(update_user_id) like", value.toUpperCase(), "updateUserId");
            return this;
        }

        public Criteria andUpdateAppLikeInsensitive(String value) {
            addCriterion("upper(update_app) like", value.toUpperCase(), "updateApp");
            return this;
        }

        public Criteria andUpdateUserIpLikeInsensitive(String value) {
            addCriterion("upper(update_user_ip) like", value.toUpperCase(), "updateUserIp");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table date_task
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}