package com.other;

import java.io.Serializable;

public class DateTask extends DateTaskKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column date_task.date_task_name
     *
     * @mbggenerated
     */
    private String dateTaskName;

    /**
     * @return the dateTaskName
     */
    public String getDateTaskName() {
      return dateTaskName;
    }

    /**
     * @param dateTaskName the dateTaskName to set
     */
    public void setDateTaskName(String dateTaskName) {
      this.dateTaskName = dateTaskName;
    }

}